- name: Install desktop apps
  hosts: localhost
  tasks:
    - name: Update cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Add PPAs
      become: true
      ansible.builtin.apt_repository:
        repo: 
        - ppa:boltgolt/howdy
        - ppa:obsproject/obs-studio
        state: present
  
    - name: Install apt apps
      become: true
      ansible.builtin.apt:
        pkg:
        - vlc
        - tilix
        - howdy
        - ffmpeg
        - flatpak
        - obs-studio
        - gnome-boxes
        - gnome-tweaks
        - fonts-firacode
        - gnome-software-plugin-flatpak
        state: latest
    
    - name: Install flatpak
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
            
    - name: Install flatpak apps
      community.general.flatpak:
        name:
        - us.zoom.Zoom
        - org.kde.okular
        - org.gnome.Music
        - org.gnome.Notes
        - org.gnome.gThumb
        - com.microsoft.Edge
        - io.bassi.Amberol
        - com.google.Chrome
        - org.audacityteam.Audacity
        - de.haeckerfelix.Fragments
        - com.rafaelmardojai.Blanket
        - org.freedesktop.Piper
        - org.freefilesync.FreeFileSync
        - com.github.unrud.VideoDownloader
        - com.github.GradienceTeam.Gradience
        - io.github.celluloid_player.Celluloid
        state: present

